### ISSUE TITLE
Ansible playbook should not mount recovery image to /mnt but to /mnt/<mountname>

### ISSUE THREAD

**Issue by JHBoricua** [jmontleon/pixelbook-fedora#25]
Currently the Ansible playbook is mounting the recovery image it downloads to /mnt rather than a directory inside /mnt. The problem is that the unmount task then proceeds to also delete the /mnt directory from the system, which it should not be doing. The other problem of mounting to /mnt is that if the user already has other mountpoints inside the /mnt tree, such as cifs/nfs shares, they become unavailable.

**Comment by jmontleon** [comment]
Thanks for the report, and sorry about that!

 Looks like I wanted `unmounted` rather than `absent` in the playbook If I was going to use /mnt.
https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html#parameter-state

To your other point, fair enough:
https://github.com/jmontleon/pixelbook-fedora/commit/d815e96cf44bdc67a28f4c8a5103272e01b3d290

Please let me know if you still have issues!
