### ISSUE TITLE
Fedora 36 does not resume after lid close

### ISSUE THREAD

**Issue by bootlessxfly** [jmontleon/pixelbook-fedora#36]
Starting with Fedora 36 and the most recent 5.17 kernel, I am no longer able to resume after closing the lid. I tried on a fresh 36 install to make sure no upgrade magic was breaking this. This appears to be kernel related - The live CD does not suffer this issue. Additionally, the most recent pixelbook kernel build (I cant remember the NVR) did not have the issue. Once I updates from the pixelbook kernel to the most recent 5.17, suspend stopped working on lid close/open. And when I would boot back into the pixelbook kernel build, things worked, However, now this pixelbook kernel is no longer in the repo.

It looks like you removed the pixelbook kernel builds from your repo. Is there anyway you can add this back? Or provide me with your patches so I can maintain a kernel build myself?

Thanks!

**Comment by jmontleon** [comment]
I stopped building the pixelbook kernels because there are no patches being carried specific to the pixelbook anymore, and no different config. The only different for quite awhile was not building the typec module. A coreboot update for the Pixelbook fixed the problem though.

If you take one of the following paths (upgrade coreboot or blacklist the typec module) it fixes the only config option I've been changing for ages. Have you done one of these? Wondering if it also affects suspend.
https://github.com/jmontleon/pixelbook-fedora/issues/26

I deleted the repo, because unfortunately, the instructions included setting a priority on the repo which meant the kernels in the copr repo took precedent over new Fedora kernels and prevent people from getting updates, which will over time be a security nightmare. I felt it was a better move to delete them.

FWIW, I just tested and I am able to suspend on lid close with Xfce and resume by opening the lid and tapping the space bar

**Comment by bootlessxfly** [comment]
I should have looked closer to the previous issues. It looks like I indeed need to update my firmware. I confirmed everything was working by blacklisting the suggested module and now I can properly resume again. Ill update my firmware later for a more permanent fix. Ill go ahead and close this!

Thanks for pointing that out!

**Comment by jmontleon** [comment]
Awesome. I'll update the existing issue to mention broken suspend too. Thank you!
