### ISSUE TITLE
Dropping to black screen and unable to use clipboard

### ISSUE THREAD

**Issue by huang-jy** [jmontleon/pixelbook-fedora#40]
Appreciate this might not be a fault of this repo but checking if anyone has suddenly started getting Fedora dropping into a black screen randomly during use on a pixelbook? Seems to happen on kernels 5.18.11 and 5.18.10, but appreciate it might actually be a recent package update elsewhere (not necessarily the kernel) but I can't find out what yet.

Also, CTRL+C suddenly decided to stop working on 5.18.11, but started working again when I unhid the grub boot menu and picked the previous kernel (5.18.10)

Behaviour sounds a bit like this: https://www.reddit.com/r/Fedora/comments/t1x07g/fedora_35_black_screen/ (also, btw, still running F35)

**Comment by jmontleon** [comment]
I have not, but I am using using Xfce. I share the same first thought as in those comments, "Sounds like a gpu driver crash."

If you're using Gnome you're likely flexing more of the 3D acceleration stuff. dmesg output might show a trace when it happens if you can ssh in when it goes black. If you can get that it'd probably go a long way to a google search to see if anyone else has hit the problem.

Fedora 36 is on the same kernel version, so unless it ends up being something else like an outdated package further up the stack, upgrading is not likely to help.

**Comment by jmontleon** [comment]
There were some i915 driver updates between 5.9 and 5.10 so not impossible:
https://git.kernel.org/stable/ds/v5.18.10/v5.18.9

**Comment by jmontleon** [comment]
And if you do find that there is a driver crash you may want to dig through the issues at https://gitlab.freedesktop.org/drm/intel/-/issues and file one if there isn't one already. My experience is that they were very busy but supper willing to help fix an issue if they could. They're the only reason we have working backlight/display brightness.

**Comment by huang-jy** [comment]
I restored my old image rom 2nd July (running Kernel 5.18.7) and everything is good, so there's definitely something between that version and now. so I'll do the upgrade and see how it goes. If it still has issues, I'll try the dmesg route and file an issue

**Comment by jmontleon** [comment]
I don't have anything new to suggest, but wondering if this is still a problem?

**Comment by huang-jy** [comment]
Ah, nah, it's not. I have upgraded to F36 since then

I will close the issue

**Comment by jmontleon** [comment]
Thank you!
