### ISSUE TITLE
USB port broken or software issue

### ISSUE THREAD

**Issue by EMLommers** [jmontleon/pixelbook-fedora#69]
One of my USB ports has suddenly given up to read / write data to port.
Charging pixelbook using this port is no problem, but using USB drives or other devices is not possible.
In my case it is the right usb-c port (if looking from sitting behind keyboard)
I have replaced the USB-C port, but no difference.

Does this behavior has to do with ACPI / Coreboot / drivers or something else?
I have seen more people are facing problems with USB port

BR,
Ernst

**Comment by jmontleon** [comment]
Have you tried resetting the laptop by using Power+Refresh? There is an issue with the left port due to a design flaw, as I understand it do with the additional debugging hardware. You can read more here:

https://support.google.com/pixelbook/thread/106922405/my-left-usb-c-port-has-stopped-working-any-solutions?hl=en

It has nothing to do with coreboot etc. and is present with ChromeOS as well where you sometimes need to do this. Day to day, aside from this occasional nuiscance I have no problem.

**Comment by EMLommers** [comment]
Thanks, no not yet.
My suzyqable gave up on me and after I made another one will do so, including update the EC to latest version (MP3)
Your opinion, wise to update? (full EC, and update UEFI, remove EC part to update)

**Comment by EMLommers** [comment]
I have updated the EC MPv3 and firmware to latest, and just switched the power input to the right side.... Left side is was ok and still is, using USB devices from left, and could run Fedora from right usb port again. .... Power is not on right... so. problem solved (in one way or another)
Thankz again!
